/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyectofrontend;

import DAO.ApiDAO;
import componentes.LoggedListener;
import vistas.VistaLogin;
import vistas.VistaReservas;


import java.util.ArrayList;
import java.util.List;

public class App {
  private static String token;
  private static ApiDAO apiDAO = new ApiDAO<>();
  private static boolean logged;
  private static List<LoggedListener> loggedListeners = new ArrayList<>();
  public static void main(String[] args) {

    VistaLogin login = new VistaLogin();
    VistaReservas reservas = new VistaReservas();

    addLoggedListener(new LoggedListener() {
      @Override
      public void onLoggedChanged(boolean logged) {
        if (logged) {
          login.setVisible(false);
          reservas.iniciarVistasReservas();
        } else {
          reservas.setVisible(false);
          login.setVisible(true);
        }
      }
    });

    login.autoclick();

  }
  public static void loggear(String token){
    App.token = token;
    logged = true;
    notifyLoggedListeners(logged);

  }

  public static void addLoggedListener(LoggedListener listener) {
    loggedListeners.add(listener);
  }

  private static void notifyLoggedListeners(boolean logged) {
    for (LoggedListener listener : loggedListeners) {
      listener.onLoggedChanged(logged);
    }
  }

  public static ApiDAO getApiDAO() {
    return apiDAO;
  }
}
