/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proyectofrontend;

import DAO.ApiDAO;
import componentes.LoggedListener;
import entidades.*;
import vistas.VistaLogin;
import vistas.VistaReservas;


import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class App {
  private static String token;
  private static ApiDAO apiDAO = new ApiDAO();
  private static boolean logged;
  private static final LocalDate hoy = LocalDate.now();
  private static List<LoggedListener> loggedListeners = new ArrayList<>();
  private static List<Reserva> reservasApi;
  private static Usuario usuario;
  private static List<Profesor> profesores;
  private static List<Asignatura> asignaturas;
  private static List<Grupo> grupos;
  private static List<Lugar> lugares;

  public static Usuario getUsuario() {
    return usuario;
  }

  public static void setUsuario(Usuario usuario) {
    App.usuario = usuario;
  }

  public static List<Reserva> getReservasApi() {
    return reservasApi;
  }

  public static void setReservasApi(List<Reserva> reservasApi) {
    App.reservasApi = reservasApi;
  }

  public static LocalDate getHoy() {
    return hoy;
  }

  public static ApiDAO getApiDAO() {
    return apiDAO;
  }

  public static List<Asignatura> getAsignaturas() {
    return asignaturas;
  }

  public static List<Grupo> getGrupos() {
    return grupos;
  }

  public static List<Lugar> getLugares() {
    return lugares;
  }

  public static List<Profesor> getProfesores() {
    return profesores;
  }

  public static void main(String[] args) {
    App.asignaturas = getApiDAO().getAsignaturas();
    App.profesores = getApiDAO().getProfesores();
    App.grupos = getApiDAO().getGrupos();
    VistaLogin login = new VistaLogin();
    VistaReservas reservas = new VistaReservas();

    addLoggedListener(new LoggedListener() {
      @Override
      public void onLoggedChanged(boolean logged) {
        if (logged) {
          login.setVisible(false);
          reservas.iniciarVistasReservas();
        } else {
          reservas.setVisible(false);
          login.setVisible(true);
        }
      }
    });

    login.autoclick();

  }

  public static void loggear(String token) {
    App.token = token;
    logged = true;
    notifyLoggedListeners(logged);

  }

  public static void addLoggedListener(LoggedListener listener) {
    loggedListeners.add(listener);
  }

  private static void notifyLoggedListeners(boolean logged) {
    for (LoggedListener listener : loggedListeners) {
      listener.onLoggedChanged(logged);
    }
  }

}
